[terminal]
shell = "fish"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[window.padding]
x = 10
y = 5

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
opacity = 0.95
decorations_theme_variant = "Light"

[general]
live_config_reload = true
import = ["./colors/gruvbox_light.toml"]
